version: '3.2'
services:
  postgres:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
    - ./database:/docker-entrypoint-initdb.d