---
platform: linux

image_resource:
  type: docker-image
  source: {repository: node, tag: '8-alpine'}

inputs:
- name: nodejsCode

outputs:
- name: nodejsCode/node_modules

run:
  path: nodejsCode/ci/scripts/install.sh