---
platform: linux

image_resource:
  type: docker-image
  source: { repository: amidos/dcind }

inputs:
  - name: nodejsCode
  - name: output/node_modules

run:
  path: nodejsCode/ci/scripts/integration-test.sh