---
resources:
- name: nodejsCode
  type: git
  source:
    uri: https://github.com/goofyahead/concourse-ci.git
    branch: master

jobs:
- name: execute-tests
  plan:
  - get: nodejsCode
  - task: install-dependencies
    file: nodejsCode/ci/tasks/install.yaml
  - task: run-test
    file: nodejsCode/ci/tasks/test.yaml