---
resources:
- name: nodejsCode
  type: git
  source:
    uri: https://github.com/goofyahead/concourse-ci.git
    branch: master

jobs:
- name: unit-tests
  plan:
  - get: nodejsCode
  - task: install-dependencies
    file: nodejsCode/ci/tasks/install.yaml
  - task: run-test
    file: nodejsCode/ci/tasks/test.yaml

jobs:
- name: integration
  plan:
  - get: nodejsCode
  - task: install-dependencies
    file: nodejsCode/ci/tasks/install.yaml
  - task: integration-tests
    privileged: true
    file: nodejsCode/ci/tasks/integration-tests.yaml