---
resource_types:
  - name: npm-cache
    type: docker-image
    source:
      repository: ymedlop/npm-cache-resource
      tag: latest

resources:
- name: nodejsCode
  type: git
  source: &repo-source
    uri: https://github.com/goofyahead/concourse-tutorial.git
    branch: develop

- name: dependency-cache
    type: npm-cache
    source:
      <<: *repo-source
      paths:
        - package.json

jobs:
- name: install dependencies
  plan:
  - get: nodejsCode
    trigger: true
  - get: dependency-cache

- name: execute tests
  plan:
  - get: nodejsCode
    passed: [Install dependencies]
  - get: dependency-cache
    passed: [Install dependencies]
  - task: run the test suite
    file: /ci/tasks/test.yml

