---
resources:
- name: nodejsCode
  type: git
  source:
    uri: https://github.com/goofyahead/concourse-ci.git
    branch: master

jobs:
- name: execute tests
  plan:
  - get: nodejsCode
  - task: install dependencies
    file: nodejsCode/ci/tasks/install.yaml
  - task: run the test suite
    file: nodejsCode/ci/tasks/test.yml