resources:
- name: nodejsCode
  type: git
  source:
    uri: https://github.com/goofyahead/concourse-tutorial.git
    branch: develop

jobs:
- name: job-hello-world
  public: true
  plan:
  - get: nodejsCode
  - task: test
    file: ./nodejsCode/test.yml
